### ISSUE TITLE
Shutdown cleanly on SIGTERM signal

### ISSUE THREAD

**Issue by trustmaster** [noflo/noflo-nodejs#118]
The runtime should listen to `process.on 'SIGKILL'` and `process.on 'SIGTERM'` and shut the main graph down when receiving them.

**Comment by jonnor** [comment]
Should only trap `SIGTERM` I think, not `SIGKILL`

**Comment by bergie** [comment]
@trustmaster for clarification: should this shut down the runtime completely, or only stop the currently running network?

**Comment by trustmaster** [comment]
@bergie what would the runtime do after stopping the current network? Auto-reload it / wait for input / become a zombie? Seems to me like shutdown is the only meaningful reaction.

**Comment by bergie** [comment]
@trustmaster that kind of depends whether it exposes the FBP protocol.

If we just stop the network, user can still connect to runtime with Flowhub and modify/restart the network.

If we stop the runtime, it is ... gone.

But I guess that's fine
