### ISSUE TITLE
Nodejs v0.12.4 server requires reset to catch graph changes

### ISSUE THREAD

**Issue by DLies** [noflo/noflo-nodejs#32]
I notice this behavior in nodejs v0.12.4 with the webserver/writeresponse component. Changes to the IIP string value for writeresponse are not reflected until I restart the service.

Once I realized this was not intended behavior, I tried using nodejs v0.10.2 and so far I have had no issues.

**Comment by jonnor** [comment]
Have not seen this problem on a recent Node.js.

Do you know if it affects nodejs 4.6 or 6.10?

**Comment by aretecode** [comment]
or 7.10...

**Comment by bergie** [comment]
Closing since there hasn't been new information.
