### ISSUE TITLE
Generate a secret if user didn't provide one

### ISSUE THREAD

**Issue by bergie** [noflo/noflo-nodejs#33]
Thanks to #7 we really want to have a secret now with noflo-nodejs. If user didn't pass one with `--secret`, we should create one.

**Comment by jonnor** [comment]
Altenatively don't enforce secret in that case? Falling back to original behavior. This is what I expected to happen. Forcing people to provide one when they don't care is unlikely to provide any real security, they'll probably use 1234 or notasecret.

**Comment by ComFreek** [comment]
See https://github.com/noflo/noflo-ui/issues/494 for what happens if you don't provide a password.

**Comment by bergie** [comment]
@jonnor yet another reason to generate a more secure password by default. Without a secret anybody could execute pretty much anything with noflo-nodejs, which is not the best idea.

**Comment by jonnor** [comment]
Fair point
