### ISSUE TITLE
Allow to build a single-file .js

### ISSUE THREAD

**Issue by jonnor** [noflo/noflo-nodejs#36]
Start-up performance of NoFlo on node.js is highly dependent on I/O usage. In some environments it can take over 1 minute to start 10 NoFlo instances.

Right now we can have caching of CoffeeScript and caching of component lookups,
but the best performance would be if we only required a single .js file. This is similar to how noflo-browser things are usualy deployed.

**Comment by jonnor** [comment]
It looks like webpack with `target: node` can do this:
http://webpack.github.io/docs/configuration.html#target

**Comment by jonnor** [comment]
Related to https://github.com/noflo/noflo/issues/157

**Comment by jonnor** [comment]
We will get an issue with finding components. For that we can take the component-cache built file, and include into bundle. Then modify NoFlo ComponentLoader to do lockup there.

**Comment by bergie** [comment]
Additionally it would be good to allow registering "external dependencies", whether they're NPM modules or other webpack bundles. This would help with things like noflo-ui's browser runtime as additional noflo-browser dependencies could be AMDd in on-demand instead of having to build a single "kitchen sink" runtime

**Comment by bergie** [comment]
grunt-noflo-browser can be used for building also Node.js bundles. Closing in favor of noflo/grunt-noflo-browser#8

**Comment by aretecode** [comment]
https://webpack.js.org/guides/code-splitting-async/
https://webpack.js.org/configuration/externals/
http://fuse-box.org:3333/page/code-splitting
