### ISSUE TITLE
Exceptions should not be silently caught

### ISSUE THREAD

**Issue by jonnor** [noflo/noflo-nodejs#44]
Right now, if one does not pass `--catch-exceptions=false` all exceptions will be silently caught.

It may be sane that we don't terminate when these happen - but they should at least be printed to stdout so we can know what is going on...

The issue is critical, because even issues with loading the initial `--graph` is swallowed. Those should probably be fatal.

**Comment by bergie** [comment]
Initial graph exceptions are now always `process.exit(1)`
