### ISSUE TITLE
Authorization - How to setup a noflo-nodejs server which only allows authorized users

### ISSUE THREAD

**Issue by cwohlman** [noflo/noflo-nodejs#7]
There's some code that looks as if it would support this but I can't find any documentation for how to secure a noflo-nodejs server against random strangers using it.

**Comment by bergie** [comment]
Related: noflo/noflo-ui#278

**Comment by jonnor** [comment]
Here is the overall of what we want to do https://github.com/noflo/noflo-ui/issues/278
This still requires a bit of work on the runtime side (in noflo-nodejs / noflo-runtime-base), not ready-for-deploy yet

**Comment by bergie** [comment]
Should work now.
